### ISSUE TITLE
AutoSize has a styling problem

### ISSUE THREAD

**Issue by JinJieTan** [bvaughn/react-virtualized-auto-sizer#12]
I downloaded the react-window@next 

左侧使用的是固定宽度和高度的 FixedSizeList

The left side USES FixedSizeList with fixed width and height

右侧使用的是react-virtualized-auto-sizer

On the right are the ruit-virtualized -auto-sizer

 
![样式表现有问题](https://user-images.githubusercontent.com/47209029/64939934-2a205700-d895-11e9-9fbc-e0570524cb05.gif)

目前遇到两个问题我很困惑：
At present, I am confused by two problems：

1.自动宽度和高度，是否把滚动条的宽度也会计算进去？ 
Auto width and height, will scroll bar width be calculated?
2.为什么自动宽度和高度有时会失效？ 一条消息的宽度竟然会重叠，样式会变成不可控制的状态

2. Why does automatic width and height sometimes fail? The width of a message can overlap, and the style can become uncontrollable
![image](https://user-images.githubusercontent.com/47209029/64939676-5d161b00-d894-11e9-8e78-72a3208e1883.png)

我用您的库重构了整个项目，这是最后遇到的问题了，也是最核心的部分，这段时间一直打扰您，不好意思。谢谢！

I used your library to reconstruct the whole project. This is the last problem I encountered, which is also the most core part. I have been disturbing you all this time. Thank you very much!

**Comment by bvaughn** [comment]
Closing bugs without repros.
