### ISSUE TITLE
Allow changing the innerElementType

### ISSUE THREAD

**Issue by pupudu** [bvaughn/react-virtualized-auto-sizer#2]
I am using this amazing library with react-window to create a virtualized table component. One issue I am facing as of now is the validateDomNesting warning I get because of the AutoSizer. 

Basically, I am experimenting a feature to allow custom element types for the windowed table. And passing element types like `p` or `tr` causes warnings from React since the AutoSizer always renders `div` tags. 

Would it be possible to allow changing the innerElementType of the Autosizer components(similar to how it is being done for components like FixedSizeList)?

Thank you very much.

**Comment by pupudu** [comment]
PS: The feature works exactly as I expect, except for the following warning,
```
Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>.
    in div (created by AutoSizer)
    in AutoSizer (at VirtualTable.js:13)
```

**Comment by Toub** [comment]
Allowing to replace `div` with `tbody` would be helpful.

**Comment by pupudu** [comment]
@Toub I don't think this will ever become a thing. I ended up copying the source code to my library and modifying the tags instead. I think for you, the best option is to fork this repo and publish a new package to npm

**Comment by Toub** [comment]
Right. This package looks to be unmaintained. :-|
