### ISSUE TITLE
Add documentation about usage

### ISSUE THREAD

**Issue by kumar303** [bvaughn/react-virtualized-auto-sizer#21]
It would be helpful if this readme documented what props AutoSizer takes and showed a brief example of usage.

**Comment by rob2d** [comment]
Not disagreeing that it'd be helpful for easier adoption, but found that the source is actually extremely clean and Flow/TS annotations are very well defined. There's basically just one component here. Props are starting @ line 11:

https://github.com/bvaughn/react-virtualized-auto-sizer/blob/master/src/index.js
