### ISSUE TITLE
API change in type Size

### ISSUE THREAD

**Issue by lfpose** [bvaughn/react-virtualized-auto-sizer#45]
Hello,
I was trying the latest version (seems like I decided to update the same time as you did).
And I wonder why this change was made and is necessary.

The type **Size** changed from
`{ height: number, width: number }` to `{ height?: number, width?: number }`
To me this seems unnecessary as there is a `defaultHeight` and `defaultWidth` props that should be used if no value is computed.

https://github.com/bvaughn/react-virtualized-auto-sizer/blob/943b6d0d4d69376f2f483201842dadbd5fc2f14d/src/AutoSizer.ts#L6-L9

**Comment by shhider** [comment]
+1, it caused typechecking problems

**Comment by Vader19695** [comment]
Also seeing a problem with this change. I would need to modify a lot of my codebase to handle this change. Heads up that reverting to v1.0.7 seems to fix the issue.

**Comment by bvaughn** [comment]
I'm sorry this changed cause type issues for you, but the new change is more  accurate type than was there prior, as both `width` and `height` params are conditional based on the `disableWidth` and `disableHeight` props.

**Comment by bvaughn** [comment]
@bennettdams That does seem like a nice DevX improvement. Thanks for the playground link.

I'd be happy to review a PR for this. Else I'll try to get around to it at some point.

**Comment by bvaughn** [comment]
Here's what I've settled on: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYQuCA7AptmAGhTgGMpcBDGXAUQBtcR8iS0BldgBSgjF1jBcAZ2KoAEgBUAsgBkAgjBhRgAIwCuNUSQBKVUjAByEACa5iAXzgAzXiDgAiCpQMOA3EiQB6L3AACMMIAtMAA5tjQuEigkLCIZM40ACK4NAYMTCx6wsAAXrhwVraYjgB0pV4Abvgm0F5maTAZzATZebjunrgAHrHwMACe-HDi0Hk4MJT07O1wALyIJADuwCYwABYAXHDY6iCqAh6owqRTuCYA6qsb27v7h0gWHj19cIPDAGoCMMCn07MLZCoda4MLrGC3PYHKBHOAnM4mcSg0LgyH3GGPZ69aD9IYFGb5eYjMa5CZTAkFABkcC+gj+FI8SHeBQAQpRhLgeHxhESgTscKRcAB+bbCZTAbChWGTUKGSjMEVw8WSjxWakAeRAwBgAB4pHJFOKNFo9TJZElgJVmiwAHyERykdbAegmCjYBxwAA+jhwbXyDhtjOZI2R4PV2HoAy5YB5CzZHOjPOpfMdztd+G2AAocvltrSfvT2gBKeY2uB6FxGUy4WFmayUdT0GBIsEwRV3aG14DCSiqRhXNZbN5QdQ1ki+kTtRXZ9p576-cnF0twSoQVaqoN4uADjbhyOJonxzm8GNwZMkVMut1ZnO4bajFSkgiL-IluZlisGYxmWu4euNmAd3WdsoQeVATG7XtGBbFEIWHUdYQnW9p1ve8STJf5X2XVd10xTxgxg8F5GwS5rnWA843ZY9uTPRZUEvdNsBvWc4ApN8P30KsfxIOsGybQi2zRTseL-PjALIkD0S7Hs+1wATFXregOWkqDcCAhSpmU8dsD9YVmNzVil3fFc1xMDcumxOJgwokNWz3KMTx5b0gPsg9vQE4jSMHRNN2GdhJhoXkSBBVshLAuE-nOASwoxY5Iq8m4dlA2K4BWQcYvMpkt108RKBIxgoCJTNcEYFo4P1WRrQIe0kJYzN2JM1YGpwsz8K3FJGiqmBdKC1BKBMExdNkbsaDwKBthyvKTAK2EKBACBqiGkb8AECbJ3yXL8oeJ4LNeUh6HZHl5E0CAKUKnpRpMHkMCwPACB1RN7X86hcDLPkxRe3rUDgELYKzDZu1KMBHLgdlbNgzygMTItSl4gCBK9b0AAYxG++FGERUM4MzAHhCBkGwY8kioccmG4f4rHEbgFGSDihEgP+p08eBmjCaxyGyOh2HRIAoCqZp77UrIxnAZZ082dbDnvNJ7n-ybPnPWR1GdpIAB9BsYFO9pxpGM0uq9JL6HoIldiN2FVYaXB0lKrJ1rvOAOqtpobdaO2DdN42Fg982wEoN0uPtir9e9D2TcbehzYoW91VUDkoGqHXdJjuOE-d8Ow7Nzx6MwSA7pgC0TGkCB1AIeq6O+0gcDFeIImwQVCiJXH8e5RlBeAaw4EzWnvqb9WTrOs9KW71Be41rX8igIG-ZYb8qSHwWR6Z0o+81s6p-92fSggJYxqSCBSD2FhB+Ht4l5X8eBHXmfqy3neBD3g+ytlsSPiEJZj4X0-AfPtffY36s4ASg+nXXAEBrAn0Xt-Mev9p4EE3tvXe+9D4EGfgBV+uAlilCDi7GA3cSx8kFj4B2JVKADFBqQQUwgeRgLgH-a+Zg4Alx+MbeaTDSgnyIZIJmP0pqMB5OcUIuAginA5DyJYIIKCnwKJXW6R91hgymM4EwZCDj4EYdgVhBBzhwAONYSIgDAhwAoB3eRPJVHYDhKkVGhDfDyDESVY2YN6BqCgH7IQPJnEAGsCjOAMEEZxgVxG-HWDw6ooM4TONgpGOAEFrDWAEEfZx8TSADH2rgdhn9e50LgQAhYo9+7ayvjk7iHDfApHiYVCgABHdQwAVCSiMW7eRW1CoSjgNAMwhVNZwnUGAV4KcBBBByAwt0nSJShAyQvIh7BcAFG7MIUccAADEAAWAAjCfduncsmwIDnAAAhF7cO+CIGAI7jjPENCk6xwEKnQ5CwHAlzrBKc4DgTmf0Fr3KO7Rk63IECbDB5Y7a-PjgITMZdjIEI+agIhABxdQfsTCg1CJQIB8AHDXIGYVegEA+BwGcVqeAPRBTnFeXAAQvAUrQphb4SujYkUHGHGEQRFAkVbI2AUD6gVekmE+qcdQoipFAujjc0FhVmnTX+d0kcFicWSkmdSuA0zZk-SUDGTYPhQjanWOoVQpQZFeFUJUBsKJsBeF8TAIIlQ6kwARc4-IJgghjyGdrLw8zRzCC8AAVi9acwWHIYCSFAKAzQOMz61XyPaJGRZYTQosDGv1X88aq2+fkEFCct6iuqGG7+2SA4JrjeSpSBQoWZLPpba2mRXa3iJOQKgyRUhOy6rpLuirUC10FImksYNHaVrKrpWNHze4VudlW7qdtSj9UGnbYaYoVpQFbW2nZ-8zDWOpb3CNURFUFo+RYLOQ7w06TtvVQdqA92C3PYUfdMjc4sCuEbAAqho4upd3nfS2Tm5NebZ5vrbuc4dja+221vL+heAHOo4N0qUOaC1cBLTnWNRd0Ll30PMImjdR7bynJ3Re-df7tln1TbgdNAhQOfMI8CrNl8IBUc-cvb91YcNgYoyKrFsNuyV2wHgAwJ6T6XrPSQPdJBRlgtA5x6upayBOivPgNd4EeYU1bHJmJCnxKDmUxBGS0FKYLEUhyDTkFZJ8105pNDn8O1mYXpu5TYoBiMF5BYZTMo5TMCJA4CClQHDKfKNBkQuCL2NyXmLHkEsIbE05o5VuFcq7wAQD9LG9p0ZRQSxFemZF7RpQ2A3PJS8uVjm7kQ9Umh-kebhOsYuLp+TwD0VAeumX1heF+uCOEEp64bGoHAEApDaEUGqAQMgZIXlQB5MUewwh1j1M8eMhVSrfAAEkuP-JvTgI+42KtItg1AawOL35TUYRyMgUwD4HRoEi+rjWsYzeVXMqhiylkADYAAcNhoCdf0RKGrXWfg4Bm+J+AxcaBQH8nZ+2HBuAnnnCIXk7SE7be3tsBw1qciyQ9DtQWf2pNpi4H7eUwhtjY8EFMHUFIyyAhVjYuA8gWqNJIgIcZmOZMWN0fojlgDsDamAFMTrVAFlzRYDyeRYTzEDaNk7c4V3bHwAONXXGqV1twAAFYCqlwUJY7IfgNJSWkvG3dGBS9RTizQ4Y0DScYkSPT+X8OZn2Zp1SAkyNnM7k1+AcxXfUwd6gVQBuAfG9N26RuI4xyf3499AHAhgeMFKM7okSNT0M5MAT3HUedPxdbHHhiieQB4yS5jVsRIc8CUHUJq3NvDP9jIg7j99X5hu+jeXT+XvnQ++wCbtM-u8mB7jyH1AYegeDEj9XhYseT4Z5x1n0og+haDnT6bzP2f4rGdSxjICRe8ONNtVACxdaXpdSQz3Sgsp5SWcFpJ1Axjti9wDXoawynjj9-tqf76Pne8R+Px8nztnGC38KN-nzUdWDB7Kb7KN6G4wC+5t5qKUjUgMRuiZij6uJZ6gw8hsR4KwjF5wCqybpFQNRQoY5xa26yQCT2gEHl7qbtKYazBWA5bdgnzNziw8hEwJTkSRZr4foobFK4AO5woIpQBIoH6orYDVzHSrzawDayL9YHD04wbVBIqjZCpJDqjSCAIgDMAQQvTRKUDWCA46KggNJTri6lJwBcLdiHYWJRwARs5s7GrOJIqf4FDWEeqpROiOimGNILJNiWFyiGArhTCOFbJLAFC1DYAADk8AEq9mHKIAM2NKrEKq7qBQSyayXqSML2hU80kinGNA3QMA7CI+MWSoIORIKwJE28pQgiMAN0YAxWJgr+dGqsDGZgJYisiAaOC8GOvsA04ysgf4LutCfsHIAAYjitQNmPflPJ0ZKN0VoXAEKEKI4EjG8unvkR0RBJKDoHngsH-IMcMTAKMSDuMasaEOsbBDMXMQ4AsUxtnIIfACseMpIHipsf0bgEMRACMXYQcXcXirMfMYsXkdcX0RMaECyBAEoCUI8cNs8TsXsZHrcZKMCaCfYN8ecb8X8dXBQAYIFrmrspvOUcCU8uMmgM4rbDxpcQNv8QXinuiTkdHkEACYcfcWAHALSbCUCSCZrCAEseSQvmRESFSRPjycyVOl0T0UyXSeMsceCFFujvkdHtQV+tiTfGAtYAGgjIKYCQyaKSyfCeyZydXJPuwQHFvHEgGnzGqYcVMfAGaeKWnmvqgB+qctbiQXJJTFAYmnRnlsnnnvcqnicYrImpAtngFOkhSV6W7iGbBEWE0Z6A6aXlpmpDya6Yqu6UGfyYOAcm7tXn6W2kmqUB6TnnzN6fmRXkWCfB7jmQGs9DQJmI-sCAlomvVt-nTBjEQYmkWepqcvGlKQvGwZch3Fga7g8tYCXAYMADgG8vXh8putWT6eCIlvFEQUvucEBBljyZ2R2Xxt3JeuThgVfn+EVNAtrPeHrDgmnEbDgd3PkiIRPESAeRPGgaqJ4Jwn5sIJ4NvjQLvsIRfFAPaCmH7hmJ3KhIZFhMZB7KjOTM2FjNsGsgAEwADM9ocAjwCab5dAOCmYn5Z0P5F4f5TEAFLED44wz4mEnBy4oFPEZezpoU8EaGa5KFH5BSE8WF9EOF+k9s+YC4xFDUZF4EFFDM1FlgyFiQqFY66FDFAgTF8e14eFBkBFT4kwnFpF4cYFvFwsNgpmqMm6rFc4dIL4JFkKe6tFQl9FV54l5cMB-5M4Bk7FhYwFZY3FMSFF0UalxaGlFBBkllgc6ERFbEy4CABlCaSAdFaFGF2sEl5luFHl2wPlIFSlJARCAQwQLwTsQQFKr25FcZTlygo4AljIQVIlIVjFZlLF0l9s0VdlsVMRCVKVvQyVqVhU6VqkfFWVNFMaQAA

**Comment by bvaughn** [comment]
1.0.18
