### ISSUE TITLE
Version 1.0.9 - Breaking Change in Output Format and Semantic Versioning

### ISSUE THREAD

**Issue by MmtBkn** [bvaughn/react-virtualized-auto-sizer#46]
Hello Maintainers,

First of all, I'd like to express my gratitude for the effort you've put into creating and maintaining this fantastic open-source project. It has been very beneficial to us, and we truly appreciate your hard work.

I'm writing to report an issue we've encountered in version 1.0.9 of the react-virtualized-auto-sizer module. It appears that the recent changes in output format have introduced a breaking change, causing one of our builds to fail. As a temporary solution, we've pinned the version to 1.0.7.

Here is the error message we encountered:
```
[2023-03-29T03:07:57.343Z] ./node_modules/react-virtualized-auto-sizer/dist/react-virtualized-auto-sizer.module.js 201:24
[2023-03-29T03:07:57.343Z]   201:24  error  Module parse failed: Unexpected token You may need an appropriate
[2023-03-29T03:07:57.343Z]                  loader to handle this file type, currently no loaders are configured to
[2023-03-29T03:07:57.343Z]                  process this file.
```

I understand that our codebase is outdated, and we are partially responsible for the issue we've encountered. However, I'd like to kindly point out that the open-source community generally adheres to semantic versioning. In my opinion, the breaking change in output format should be marked as a major release, helping users to be aware of the potential issues before updating their dependencies.

I understand that maintaining an open-source project can be challenging, and I want to emphasize that we appreciate all your hard work. I hope this bug report is helpful to you and the community. If you need any further information or assistance in resolving this issue, please don't hesitate to ask.

Thank you and best regards

**Comment by BlueRexPY** [comment]
Try to use this in your webpack config, it worked for me

```
{
        test: /\.js$/,
        include: [path.resolve(__dirname, 'src'), /node_modules[\/]@?react-virtualized-auto-sizer/],
        use: {
          loader: 'babel-loader',
          options: {
            presets: [['@babel/preset-env', { modules: false }], '@babel/preset-react'],
            plugins: ['@babel/plugin-proposal-class-properties'],
          },
        },
      },
 ```

**Comment by floriancargoet** [comment]
I have the same issue, but it's when I run storybook (which uses webpack & babel).

**Comment by bvaughn** [comment]
Sorry about the unexpected change in a minor release 🙇🏼  It wasn't intentional, just an oversight.

It would be helpful to have a repro so I could verify if a change on my side fixes this.

**Comment by bvaughn** [comment]
I _think_ that using the `@babel/plugin-proposal-class-properties` plugin might fix this.

**Comment by bvaughn** [comment]
Try 1.0.11 (just published). Hopefully it fixes this. If not, please share a repro!

**Comment by rybesh** [comment]
Was there [a switch from an older version of Babel](https://stackoverflow.com/a/33705077)?

I’m using browserify and importing like this:

```js
AutoSizer = require('react-virtualized-auto-sizer')
```

The error I get (even with 1.0.11) is:

```
[Error] Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
[Error] Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

Changing to:

```js
AutoSizer = require('react-virtualized-auto-sizer’).default
```

… fixes the issue.
