### ISSUE TITLE
Reporting an integer size when the available space has decimals

### ISSUE THREAD

**Issue by DiegoBM** [bvaughn/react-virtualized-auto-sizer#57]
Sometimes Chrome reports a height that has decimals, but autosizer will return the next integer number, therefore resulting in more space than what's available on screen. At the moment I'm solving it by always removing one to the result returned by autosize, but if I could get the height as reported by Chrome with the decimals, the problem would be solved even if it's passed as pixels to CSS.

**Comment by bvaughn** [comment]
I'm not sure what's being requested. AutoSizer returns the bounding client rect width/height as well as the offsetWidth/offsetHeight:

https://github.com/bvaughn/react-virtualized-auto-sizer/blob/c644cfd0c348faeefabbe219c472ab87993eab88/src/AutoSizer.ts#L199-L203

The only _rounding_ that's being done is for padding:

https://github.com/bvaughn/react-virtualized-auto-sizer/blob/c644cfd0c348faeefabbe219c472ab87993eab88/src/AutoSizer.ts#L192-L196

Is that where the decimal values are coming from? (Can you provide some sort of repro?)

**Comment by DiegoBM** [comment]
It might be the rounding happening in the paddings then, since Chrome is reporting the paddings with decimals, but the final height returned by auto-sizer came back as an integer, causing the original issue with the scrollbars appearing. Picture attached:

![image](https://github.com/bvaughn/react-virtualized-auto-sizer/assets/1613216/f4430469-36c9-468e-9964-68ca4e746d76)

**Comment by bvaughn** [comment]
Can you share a repro? Screenshots aren't really that helpful when it comes to verifying fixes.

**Comment by DiegoBM** [comment]
I'm afraid I don't, I ended up removing the library a couple of weeks ago due to the rounded sizes when Chrome reported decimals, since it was causing scrollbars to appear in the container as mentioned above. In any case if I find myself needing the library again I know where the issue is. Thanks

**Comment by srijanchandrakar** [comment]
is it the same issue where the scroll bar flikers?
