### ISSUE TITLE
"react-virtualized-auto-sizer 新版本重复渲染子组件，和 antd tabs 冲突

### ISSUE THREAD

**Issue by controllerz** [bvaughn/react-virtualized-auto-sizer#58]
我之前用的是"react-virtualized-auto-sizer": "1.0.7"版本， 
最近更新的比较快。发布时候找到最新的版本，结果 antd  tabs有冲突， tab1 和 tab2 切换会重新渲染组件。 
起初我以为是antd 问题。 锁板还能复现。 
最后排查react-virtualized-auto-sizer 这个东西 会重新更新内容， antd tabs 都缓存不了展示过的内容。
这对性能来说是一个很严重的问题。 
![image](https://user-images.githubusercontent.com/22693880/233831602-593854d9-0118-4e6d-aa54-0cf66ba9a4d3.png)

**Comment by bvaughn** [comment]
请分享我可以运行的代码并查看您所指的问题。 仅共享代码图片是不够的。

**Comment by bvaughn** [comment]
我正在关闭这个问题，因为没有办法重现它。
