### ISSUE TITLE
API change in return type

### ISSUE THREAD

**Issue by markmcdowell** [bvaughn/react-virtualized-auto-sizer#59]
Hello, I've just moved to the latest version and I can't compile in typescript due the changes to the children function.

Previous [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/05663f015e3d72c8ded01ac424f69310adae1572/types/react-virtualized-auto-sizer/index.d.ts#L16) used `ReactNode` and it seems this has changed to `ReactElement`. This means I can't return `null` anymore.

Was this intentional? Our use case if the the space is less than a set breakpoint we hide the element.

Thanks!

https://github.com/bvaughn/react-virtualized-auto-sizer/blob/943b6d0d4d69376f2f483201842dadbd5fc2f14d/src/AutoSizer.ts#L12

**Comment by bvaughn** [comment]
Not intentional. Most likely an oversight in a larger refactoring.

Fixed in 1.0.16

**Comment by markmcdowell** [comment]
Awesome thanks very much.
