### ISSUE TITLE
1.0.19 does not render anything

### ISSUE THREAD

**Issue by floklein** [bvaughn/react-virtualized-auto-sizer#67]
Hi!

We use your lib in our React app. We updated from 1.0.17 to 1.0.20. Our build stack includes:
- Typescript
- Esbuild
- Webpack
- Turborepo

1.0.19 only renders an empty div. No errors.

![before](https://github.com/bvaughn/react-virtualized-auto-sizer/assets/4128942/02191842-437f-4e70-af04-3cf58b84a3bd)
![after](https://github.com/bvaughn/react-virtualized-auto-sizer/assets/4128942/520868e3-3d47-4d83-a473-5659d7b41125)

**Comment by bvaughn** [comment]
Please share a runnable repro. Can't do anything with this otherwise.
