### ISSUE TITLE
Testing Component using AutoSizer

### ISSUE THREAD

**Issue by omhoumz** [bvaughn/react-virtualized-auto-sizer#7]
In [your tests](https://github.com/bvaughn/react-virtualized-auto-sizer/blob/master/src/__tests__/AutoSizer.js) (@bvaughn), I see that you are mocking the `OffsetSize` and adding `_mountNode` to the `document.body`.

If I want to test a component that's using the `AutoSizer`, how can I do this without exposing the implementation details of the component?

PS: I'm using `jest` and `enzyme`

**Comment by bvaughn** [comment]
I think the easiest way is to just bypass auto sizer in your own tests. The resizing behavior is probably not the thing you're trying to test anyway.

**Comment by bvaughn** [comment]
(We can keep chatting here but I'm going to close this issue since there's no action to be taken)

**Comment by omhoumz** [comment]
In my tests, I want to check for the components rendered inside the AutoSizer, when I check the render output, I find nothing.

**Comment by bvaughn** [comment]
You don't actually need to test the auto-sizing logic, right? That's covered by my tests. You're just concerned with testing your own components. This is why I suggested you _bypass_ auto-sizer, either by just calling the inner components directly _or_ by adding some test-only prop for fixed width/height.

**Comment by omhoumz** [comment]
Yes, I understand.
I set up a [repo](https://github.com/omhoumz/t001) to showcase what I want to do.

In this test I'm trying to check the html of the `Comp` (that contains the AutoSizer). I get nothing.
```jsx
it('...', () => {
  const wrapper = mount(<Comp />)
  console.log(wrapper.html())
  [...]
})
```

**Comment by bvaughn** [comment]
I feel like we're talking past each other. I'll refer to my comment above:
> This is why I suggested you bypass auto-sizer, either by just calling the inner components directly or by adding some test-only prop for fixed width/height.

Your test does neither of these, right?

**Comment by quangta93** [comment]
@bvaughn could you suggest how I can bypass auto-sizer in this case? I am using `react-testing-library`. I could instead test `ComponentUsingList.js` but that won't test whether `CustomRow`s are rendered correctly according to `data`.

![autosizer](https://user-images.githubusercontent.com/2924390/62646717-901fd300-b914-11e9-8aac-ba7de04ec819.png)

**Comment by bvaughn** [comment]
Why do you need to test `ComponentUsingList` in the above example? It doesn't really do anything interesting other than passing in `width` and `height` which you could just pass directly to `FixedSizeList`.  Your tests don't need to cover `AutoSizer`. I have tests for it (in this repo).

**Comment by quangta93** [comment]
@bvaughn thanks for a surprisingly quick reply!

The screenshot is a simplified version. To clarify, `ComponentUsingList` is doing other things (e.g. sticky header) so it isn't simply pass width and height to `FixedSizeList`. `ComponentUsingList` is used in several components like `ComponentUsingComponentUsingList`. Hence, the need to test `ComponentUsingComponentUsingList`.

My problem right now is that the test fails because `AutoSizer` won't render any row component. How should I structure my components & tests so that my test works? From your comment, I am guessing make `AutoSizer` the parent of `ComponentUsingComponentUsingList` and pass `width` and `height` all the way down to `FixedSizeList` (possibly by context). Is that correct?

**Comment by bvaughn** [comment]
You have a few options then.

You can pass in an explicit width/height props (for testing only) and use those as the `defaultHeight` and `defaultWidth` for `AutoSizer` when present.

Or you can mock out the portion of the browser API that `AutoSizer` users to measure itself:
https://github.com/bvaughn/react-virtualized-auto-sizer/blob/ffcba2dd39b89111ed4b42d64431f35ce7c1c23a/src/__tests__/AutoSizer.js#L90-L101
