### ISSUE TITLE
TypeScript: Incorrect typing of AutoSize height and width

### ISSUE THREAD

**Issue by melloware** [bvaughn/react-virtualized-auto-sizer#72]
I am upgrading an old library from react-virtualized and it was doing this.

```xml
<AutoSizer
          disableHeight={this.props.height !== "auto"}
          disableWidth={this.props.width !== "auto"}
        >
          {({ height, width }) => (
```

When upgrading to this library its now saying `height` and `width` are not valid because my props are defaulted to `auto` but allow the user to change.

![image](https://github.com/bvaughn/react-virtualized-auto-sizer/assets/4399574/3068cf9d-91ef-41b1-a724-25535ebcc902)

**Comment by bvaughn** [comment]
The type warnings are intentional (and correct)
 
Please see the recent discussion on #70

**Comment by melloware** [comment]
Thank for the great library!   I understand your design decision but something to remember.

> A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools. - Douglas Adams
