### ISSUE TITLE
Typings for conditional `disableHeight` and `disableWidth`

### ISSUE THREAD

**Issue by DenizUgur** [bvaughn/react-virtualized-auto-sizer#73]
These props should accept `boolean` and children props type can utilize Partial if there is no better option.

**Comment by bvaughn** [comment]
The types were intentionally chosen as explained in comments like this one https://github.com/bvaughn/react-virtualized-auto-sizer/pull/71#issuecomment-1638437808. It's okay if you don't agree, but I'm not going to change them based on a subjective assertion.

**Comment by DenizUgur** [comment]
I understand that you may not want to change it. It's just that following use case works without a problem but types indicate there is a problem. I see this as a reasonable use case for responsiveness. If you have any other suggestion, please let me know.

```jsx
<AutoSizer disableHeight={mobile}>
    {({ height, width }) => {
        return (
            <List
                height={height || 500}
                itemCount={results.boxes[type].length}
                itemData={results.boxes[type]}
                itemSize={26}
                width={width}
            >
                {Row}
            </List>
        );
    }}
</AutoSizer>
```
