### ISSUE TITLE
'AutoSizer' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by IbrahimIjai** [bvaughn/react-virtualized-auto-sizer#74]
How can I fix this error please??

"'AutoSizer' cannot be used as a JSX component.
  Its instance type 'AutoSizer' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786"

It seems to be a minor issue but I cant get my head around it

Here is my component

'use client'

import React, { CSSProperties, FC, ReactElement, useCallback } from 'react'
import AutoSizer from 'react-virtualized-auto-sizer'
import { FixedSizeList } from 'react-window'

type RowCallback<TData> = (row: { index: number; style: CSSProperties }) => ReactElement

export interface ListProps<TData> {
  className?: string
  rowHeight?: number
  rowRenderer: FC<TData>
  rowData: TData[]
}

export type ListComponent = <TData>(props: ListProps<TData>) => React.ReactElement | null

export function List<TData>({ className, rowHeight, rowData, rowRenderer: RowComponent }: ListProps<TData>) {
  const Row = useCallback<RowCallback<TData>>(
    ({ index, style }) => {
      return <RowComponent style={style} {...rowData[index]} />
    },
    [RowComponent, rowData]
  )

  return (
    <AutoSizer >
      {({ height }: { height: number }) => (
        <FixedSizeList
          width="100%"
          height={height}
          itemCount={rowData.length}
          itemSize={rowHeight || 48}
          className={className}
          style={{ overflow: 'overlay' }}
        >
          {Row}
        </FixedSizeList>
      )}
    </AutoSizer>
  )
}

**Comment by bvaughn** [comment]
Change published in react-virtualized-auto-sizer@1.0.21

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
