### ISSUE TITLE
Is it possible to render content inside auto sizer callback on server?

### ISSUE THREAD

**Issue by zubairhasrat** [bvaughn/react-virtualized-auto-sizer#75]
I want to render content inside callback in auto sizer to be rendered on server is that possible?
```
<AutoSizer>
   {() => <div>this needs to be server side rendered</div>}
</AutoSizer>
```

**Comment by bvaughn** [comment]
Use the defaultHeight and defaultWidth props for this. As the docs mention, they are for server rendering fallback.
