### ISSUE TITLE
AutoSizer not rendering initially with consistent height for fixed height components

### ISSUE THREAD

**Issue by pzhang24** [bvaughn/react-virtualized-auto-sizer#76]
Hi,

I have a case where AutoSizer only manages the width of the child component. It's similar to the example given in the FAQ:

`<AutoSizer disableHeight>
  {({width}) => <Component height={200} width={width} {...props} />}
</AutoSizer>`

However, I’ve noticed that AutoSizer skips rendering the child component on its initial render since the width it initially calculates is zero. Since I’m specifying a fixed height for the child component, I would like for it to take up the height I specified even on the initial render. 

In my specific case, I am trying to render a virtualized list of items, where the item uses AutoSizer when it is in view, but uses a different component when it is not. When I try to scroll up from the bottom of the list, the list sometimes doesn't scroll properly. This seems to be because the height of items being scrolled into view changes between the initial and subsequent render.

[CodeSandbox Link](https://codesandbox.io/p/sandbox/autosizer-experiment-little-voice-k4vwwj-k4vwwj?file=%2Fsrc%2FAutosizedComponent.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo3egwxs000a3b6le1t9kyiv%2522%252C%2522sizes%2522%253A%255B56.626506024096386%252C43.373493975903614%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo3egwxs00033b6lgobhmzya%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo3egwxs00073b6lbbyaivsa%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo3egwxs00093b6lzyv1x129%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo3egwxs00033b6lgobhmzya%2522%253A%257B%2522id%2522%253A%2522clo3egwxs00033b6lgobhmzya%2522%252C%2522activeTabId%2522%253A%2522cloousl2x00nj3b6mtkuf9yzc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo3egwxs00023b6lis38dptr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clo3ehekh007a3b6lkl3ji4d3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FAutosizedComponent.tsx%2522%252C%2522id%2522%253A%2522clo3f00cj01p63b6lmqvs69si%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FNonAutosizedComponent.tsx%2522%252C%2522id%2522%253A%2522clo3f64dl029t3b6l5kfepnlq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.css%2522%252C%2522id%2522%253A%2522clo3fmkll03p23b6l5f1jy9t1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.css%2522%252C%2522id%2522%253A%2522clo3gihl401tm3b6lz405oxw8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522id%2522%253A%2522clo3gjgei02113b6lg0e8b15o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clo3gqh2n03zt3b6lj5b3xepr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FComponentWithVisibilityCheck.tsx%2522%252C%2522id%2522%253A%2522clo3ht31a0c6h3b6le5opc9cj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522id%2522%253A%2522cloousl2x00nj3b6mtkuf9yzc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fvite.config.ts%2522%252C%2522id%2522%253A%2522cloovrfxh025t3b6m8zdn60nh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fvite-env.d.ts%2522%252C%2522id%2522%253A%2522cloovvmqu02og3b6mbutlalme%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fyarn.lock%2522%252C%2522id%2522%253A%2522cloowes0203q63b6m2oqutk3m%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522id%2522%253A%2522cloox5fpb05ga3b6mlzxq8gw1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.eslintrc.cjs%2522%252C%2522id%2522%253A%2522cloox5pgk05l23b6m1akad78t%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clo3egwxs00093b6lzyv1x129%2522%253A%257B%2522id%2522%253A%2522clo3egwxs00093b6lzyv1x129%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloouyucx016t3b6m4wh1b15d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloouyucx016t3b6m4wh1b15d%2522%257D%252C%2522clo3egwxs00073b6lbbyaivsa%2522%253A%257B%2522id%2522%253A%2522clo3egwxs00073b6lbbyaivsa%2522%252C%2522activeTabId%2522%253A%2522clo3egwxs00043b6lq9kmu9o5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo3egwxs00043b6lq9kmu9o5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clo3egwxs00063b6l0keu451p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522cloouyawx012g3b6mqbgclpzk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cloowi3tr043k3b6mhdjo7uei%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloowi402001pefiffe1pfh3o%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A25.383597883597886%257D)

I was wondering if the AutoSizer implementation could be changed so that the child component should be rendered whenever the client fixes one of the dimensions (ie either disableWidth or disableHeight is true), regardless of whether the other dimension controlled by AutoSizer is zero or not?

(If not, I could work around it by passing a non-zero value for defaultWidth so the initial render isn't skipped. Just wanted to bring this issue up in case this is something that should be fixed.)

**Comment by bvaughn** [comment]
> I was wondering if the AutoSizer implementation could be changed so that the child component should be rendered whenever the client fixes one of the dimensions (ie either disableWidth or disableHeight is true), regardless of whether the other dimension controlled by AutoSizer is zero or not?

I don't think this would make sense, with the current design of the component. It doesn't make sense to render a 0-width or 0-height anything.

> If not, I could work around it by passing a non-zero value for defaultWidth so the initial render isn't skipped. Just wanted to bring this issue up in case this is something that should be fixed.)

Yeah, this would be my recommendation! 👍🏼

**Comment by bvaughn** [comment]
Going to close this as it seems to have been resolved.
