### ISSUE TITLE
Is it possible to measure an "itemSize" prop dynamically?

### ISSUE THREAD

**Issue by Lenur29** [bvaughn/react-virtualized-auto-sizer#91]
I use "react-window" and "react-virtualized-auto-sizer". For example inisde the VariableSizeList component I render items. Each of them can have its own height. I do not know it in advance, because it depends on the text content. For example, one item can have short description another one long. Is it possible to measure an "itemSize" prop dynamically?

**Comment by bvaughn** [comment]
Check out the discussion on this issue: https://github.com/bvaughn/react-window/issues/190

**Comment by Lenur29** [comment]
@bvaughn Sorry, I missed this message from you( I checked out the discussion you shared above. As I understood it is stll not supported? If I misunderstood that discussion, please inform me 🙏

**Comment by bvaughn** [comment]
It’s still not supported, but that thread explains some workarounds.

**Comment by Lenur29** [comment]
@bvaughn Thank you 🙏
