### ISSUE TITLE
Is it possible to determine an "itemSize" prop dynamically during render?

### ISSUE THREAD

**Issue by Lenur29** [bvaughn/react-virtualized-auto-sizer#92]
I use react-window and react-virtualized-auto-sizer. I render items inside VariableSizeList component. But I do not know the size of the items in advance. It depends on content each item include(ite can be very different). Is it possible to determine an "itemSize" prop dynamically during render using refs or something else?

**Comment by bvaughn** [comment]
Same thing as i said on your other issue #91, check out the discussion on this issue: https://github.com/bvaughn/react-window/issues/190
